-- IDP v3.2.2 지부 설립 신청 PATCH
-- Supabase > SQL Editor에서 전체 실행
-- 목적: PGRST202 RPC 문제를 우회하고, 공개 사용자는 신청 INSERT만 허용합니다.

-- 테이블이 이미 있어도 안전하게 실행됩니다.
create table if not exists public.idp_branch_applications (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

alter table public.idp_branch_applications add column if not exists branch_type text;
alter table public.idp_branch_applications add column if not exists branch_level text;
alter table public.idp_branch_applications add column if not exists country text;
alter table public.idp_branch_applications add column if not exists region text;
alter table public.idp_branch_applications add column if not exists applicant_name text;
alter table public.idp_branch_applications add column if not exists phone text;
alter table public.idp_branch_applications add column if not exists email text;
alter table public.idp_branch_applications add column if not exists organization text;
alter table public.idp_branch_applications add column if not exists drone_qualification text;
alter table public.idp_branch_applications add column if not exists safety_experience text;
alter table public.idp_branch_applications add column if not exists expected_members integer;
alter table public.idp_branch_applications add column if not exists service_area text;
alter table public.idp_branch_applications add column if not exists plan text;
alter table public.idp_branch_applications add column if not exists notes text;
alter table public.idp_branch_applications add column if not exists status text default 'pending';
alter table public.idp_branch_applications add column if not exists admin_note text;

update public.idp_branch_applications set status='pending' where status is null;
alter table public.idp_branch_applications alter column status set default 'pending';

alter table public.idp_branch_applications enable row level security;

grant usage on schema public to anon, authenticated;
grant insert on public.idp_branch_applications to anon, authenticated;
grant select, update on public.idp_branch_applications to authenticated;

-- 공개 방문자는 새 신청서를 넣을 수만 있고, 다른 신청서는 읽을 수 없습니다.
drop policy if exists "IDP public insert branch applications" on public.idp_branch_applications;
create policy "IDP public insert branch applications"
on public.idp_branch_applications
for insert
to anon, authenticated
with check (
  coalesce(status,'pending') = 'pending'
  and nullif(trim(coalesce(branch_type,'')),'') is not null
  and nullif(trim(coalesce(branch_level,'')),'') is not null
  and nullif(trim(coalesce(country,'')),'') is not null
  and nullif(trim(coalesce(region,'')),'') is not null
  and nullif(trim(coalesce(applicant_name,'')),'') is not null
  and nullif(trim(coalesce(phone,'')),'') is not null
  and nullif(trim(coalesce(email,'')),'') is not null
  and nullif(trim(coalesce(plan,'')),'') is not null
);

-- 관리자만 신청서 조회/상태수정
drop policy if exists "IDP admin read branch applications" on public.idp_branch_applications;
create policy "IDP admin read branch applications"
on public.idp_branch_applications
for select to authenticated
using ((auth.jwt() ->> 'email')='jeonseongkweon@gmail.com');

drop policy if exists "IDP admin update branch applications" on public.idp_branch_applications;
create policy "IDP admin update branch applications"
on public.idp_branch_applications
for update to authenticated
using ((auth.jwt() ->> 'email')='jeonseongkweon@gmail.com')
with check ((auth.jwt() ->> 'email')='jeonseongkweon@gmail.com');

-- identity/sequence 방식 차이에 대비해 sequence 권한도 보강
DO $$
DECLARE r record;
BEGIN
  FOR r IN
    SELECT sequence_schema, sequence_name
    FROM information_schema.sequences
    WHERE sequence_schema='public'
      AND sequence_name ILIKE 'idp_branch_applications%'
  LOOP
    EXECUTE format('grant usage, select on sequence %I.%I to anon, authenticated', r.sequence_schema, r.sequence_name);
  END LOOP;
END $$;

-- PostgREST schema cache 즉시 갱신 요청
notify pgrst, 'reload schema';

select 'IDP v3.2.2 PATCH READY' as result;
