-- IDP v3.2 지부 설립신청 + 17개 시도 조직관리 테이블
-- Supabase SQL Editor에서 1회 실행

create table if not exists public.idp_branch_applications (
 id bigint generated by default as identity primary key, created_at timestamptz not null default now(), branch_type text not null, branch_level text not null, country text not null, region text not null, applicant_name text not null, phone text not null, email text not null, organization text, drone_qualification text, safety_experience text, expected_members integer, service_area text, plan text not null, notes text, status text not null default 'pending', admin_note text
);
alter table public.idp_branch_applications enable row level security;
drop policy if exists "IDP public insert branch applications" on public.idp_branch_applications;
create policy "IDP public insert branch applications" on public.idp_branch_applications for insert to anon, authenticated with check (true);
drop policy if exists "IDP admin read branch applications" on public.idp_branch_applications;
create policy "IDP admin read branch applications" on public.idp_branch_applications for select to authenticated using ((auth.jwt() ->> 'email')='jeonseongkweon@gmail.com');
drop policy if exists "IDP admin update branch applications" on public.idp_branch_applications;
create policy "IDP admin update branch applications" on public.idp_branch_applications for update to authenticated using ((auth.jwt() ->> 'email')='jeonseongkweon@gmail.com') with check ((auth.jwt() ->> 'email')='jeonseongkweon@gmail.com');

create table if not exists public.idp_branch_profiles (region_slug text primary key, region_name text not null, headquarters_name text not null, status text not null default 'building', introduction text, updated_at timestamptz default now());
alter table public.idp_branch_profiles enable row level security;
drop policy if exists "IDP public read branch profiles" on public.idp_branch_profiles;
create policy "IDP public read branch profiles" on public.idp_branch_profiles for select to anon, authenticated using (true);
drop policy if exists "IDP admin manage branch profiles" on public.idp_branch_profiles;
create policy "IDP admin manage branch profiles" on public.idp_branch_profiles for all to authenticated using ((auth.jwt() ->> 'email')='jeonseongkweon@gmail.com') with check ((auth.jwt() ->> 'email')='jeonseongkweon@gmail.com');

create table if not exists public.idp_branch_officers (id bigint generated by default as identity primary key, region_slug text not null references public.idp_branch_profiles(region_slug) on delete cascade, role text not null, name text, phone text, email text, area text, photo_url text, is_public boolean not null default true, sort_order integer not null default 100, updated_at timestamptz default now(), unique(region_slug,role));
alter table public.idp_branch_officers enable row level security;
drop policy if exists "IDP public read branch officers" on public.idp_branch_officers;
create policy "IDP public read branch officers" on public.idp_branch_officers for select to anon, authenticated using (is_public=true);
drop policy if exists "IDP admin manage branch officers" on public.idp_branch_officers;
create policy "IDP admin manage branch officers" on public.idp_branch_officers for all to authenticated using ((auth.jwt() ->> 'email')='jeonseongkweon@gmail.com') with check ((auth.jwt() ->> 'email')='jeonseongkweon@gmail.com');

insert into public.idp_branch_profiles(region_slug, region_name, headquarters_name, status) values ('seoul','서울특별시','서울특별본부','building') on conflict(region_slug) do nothing;
insert into public.idp_branch_profiles(region_slug, region_name, headquarters_name, status) values ('busan','부산광역시','부산광역본부','building') on conflict(region_slug) do nothing;
insert into public.idp_branch_profiles(region_slug, region_name, headquarters_name, status) values ('daegu','대구광역시','대구광역본부','building') on conflict(region_slug) do nothing;
insert into public.idp_branch_profiles(region_slug, region_name, headquarters_name, status) values ('incheon','인천광역시','인천광역본부','building') on conflict(region_slug) do nothing;
insert into public.idp_branch_profiles(region_slug, region_name, headquarters_name, status) values ('gwangju','광주광역시','광주광역본부','building') on conflict(region_slug) do nothing;
insert into public.idp_branch_profiles(region_slug, region_name, headquarters_name, status) values ('daejeon','대전광역시','대전광역본부','building') on conflict(region_slug) do nothing;
insert into public.idp_branch_profiles(region_slug, region_name, headquarters_name, status) values ('ulsan','울산광역시','울산광역본부','building') on conflict(region_slug) do nothing;
insert into public.idp_branch_profiles(region_slug, region_name, headquarters_name, status) values ('sejong','세종특별자치시','세종특별본부','building') on conflict(region_slug) do nothing;
insert into public.idp_branch_profiles(region_slug, region_name, headquarters_name, status) values ('gyeonggi','경기도','경기본부','building') on conflict(region_slug) do nothing;
insert into public.idp_branch_profiles(region_slug, region_name, headquarters_name, status) values ('gangwon','강원특별자치도','강원본부','building') on conflict(region_slug) do nothing;
insert into public.idp_branch_profiles(region_slug, region_name, headquarters_name, status) values ('chungbuk','충청북도','충북본부','building') on conflict(region_slug) do nothing;
insert into public.idp_branch_profiles(region_slug, region_name, headquarters_name, status) values ('chungnam','충청남도','충남본부','building') on conflict(region_slug) do nothing;
insert into public.idp_branch_profiles(region_slug, region_name, headquarters_name, status) values ('jeonbuk','전북특별자치도','전북본부','building') on conflict(region_slug) do nothing;
insert into public.idp_branch_profiles(region_slug, region_name, headquarters_name, status) values ('jeonnam','전라남도','전남본부','building') on conflict(region_slug) do nothing;
insert into public.idp_branch_profiles(region_slug, region_name, headquarters_name, status) values ('gyeongbuk','경상북도','경북본부','building') on conflict(region_slug) do nothing;
insert into public.idp_branch_profiles(region_slug, region_name, headquarters_name, status) values ('gyeongnam','경상남도','경남본부','building') on conflict(region_slug) do nothing;
insert into public.idp_branch_profiles(region_slug, region_name, headquarters_name, status) values ('jeju','제주특별자치도','제주본부','building') on conflict(region_slug) do nothing;
