-- IDP v3.2.1 지부 설립 신청 HOTFIX
-- Supabase > SQL Editor 에서 전체를 한 번 실행하세요.
-- 여러 번 실행해도 안전하도록 구성했습니다.

-- 1) 테이블 구조 보강: 기존 테이블이 있어도 빠진 컬럼을 추가합니다.
create table if not exists public.idp_branch_applications (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

alter table public.idp_branch_applications add column if not exists branch_type text;
alter table public.idp_branch_applications add column if not exists branch_level text;
alter table public.idp_branch_applications add column if not exists country text;
alter table public.idp_branch_applications add column if not exists region text;
alter table public.idp_branch_applications add column if not exists applicant_name text;
alter table public.idp_branch_applications add column if not exists phone text;
alter table public.idp_branch_applications add column if not exists email text;
alter table public.idp_branch_applications add column if not exists organization text;
alter table public.idp_branch_applications add column if not exists drone_qualification text;
alter table public.idp_branch_applications add column if not exists safety_experience text;
alter table public.idp_branch_applications add column if not exists expected_members integer;
alter table public.idp_branch_applications add column if not exists service_area text;
alter table public.idp_branch_applications add column if not exists plan text;
alter table public.idp_branch_applications add column if not exists notes text;
alter table public.idp_branch_applications add column if not exists status text;
alter table public.idp_branch_applications add column if not exists admin_note text;

update public.idp_branch_applications set status='pending' where status is null;
alter table public.idp_branch_applications alter column status set default 'pending';

-- 2) 관리자는 로그인 후 신청서를 조회/수정할 수 있습니다.
alter table public.idp_branch_applications enable row level security;

drop policy if exists "IDP admin read branch applications" on public.idp_branch_applications;
create policy "IDP admin read branch applications"
on public.idp_branch_applications for select to authenticated
using ((auth.jwt() ->> 'email')='jeonseongkweon@gmail.com');

drop policy if exists "IDP admin update branch applications" on public.idp_branch_applications;
create policy "IDP admin update branch applications"
on public.idp_branch_applications for update to authenticated
using ((auth.jwt() ->> 'email')='jeonseongkweon@gmail.com')
with check ((auth.jwt() ->> 'email')='jeonseongkweon@gmail.com');

grant usage on schema public to anon, authenticated;
grant select, update on public.idp_branch_applications to authenticated;

-- 3) 공개 신청은 테이블 직접 INSERT 대신 보안 함수(RPC)로 받습니다.
--    status/admin_note를 외부 신청자가 임의로 넣을 수 없고,
--    프로젝트별 INSERT/sequence 권한 차이에도 영향을 덜 받습니다.
create or replace function public.submit_idp_branch_application(
  p_branch_type text,
  p_branch_level text,
  p_country text,
  p_region text,
  p_applicant_name text,
  p_phone text,
  p_email text,
  p_organization text default null,
  p_drone_qualification text default null,
  p_safety_experience text default null,
  p_expected_members integer default null,
  p_service_area text default null,
  p_plan text default null,
  p_notes text default null
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  if nullif(trim(coalesce(p_branch_type,'')),'') is null
     or nullif(trim(coalesce(p_branch_level,'')),'') is null
     or nullif(trim(coalesce(p_country,'')),'') is null
     or nullif(trim(coalesce(p_region,'')),'') is null
     or nullif(trim(coalesce(p_applicant_name,'')),'') is null
     or nullif(trim(coalesce(p_phone,'')),'') is null
     or nullif(trim(coalesce(p_email,'')),'') is null
     or nullif(trim(coalesce(p_plan,'')),'') is null then
    raise exception '필수 신청정보가 누락되었습니다.' using errcode='22023';
  end if;

  insert into public.idp_branch_applications(
    branch_type,branch_level,country,region,applicant_name,phone,email,
    organization,drone_qualification,safety_experience,expected_members,
    service_area,plan,notes,status
  ) values (
    trim(p_branch_type),trim(p_branch_level),trim(p_country),trim(p_region),
    trim(p_applicant_name),trim(p_phone),trim(p_email),nullif(trim(coalesce(p_organization,'')),''),
    nullif(trim(coalesce(p_drone_qualification,'')),''),nullif(trim(coalesce(p_safety_experience,'')),''),
    p_expected_members,nullif(trim(coalesce(p_service_area,'')),''),trim(p_plan),
    nullif(trim(coalesce(p_notes,'')),''),'pending'
  ) returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.submit_idp_branch_application(text,text,text,text,text,text,text,text,text,text,integer,text,text,text) from public;
grant execute on function public.submit_idp_branch_application(text,text,text,text,text,text,text,text,text,text,integer,text,text,text) to anon, authenticated;

-- 기존 공개 직접 INSERT 정책은 더 이상 필요하지 않습니다.
drop policy if exists "IDP public insert branch applications" on public.idp_branch_applications;
revoke insert on public.idp_branch_applications from anon;

-- 4) 17개 시·도 조직 공개조회/관리자 수정 권한도 확실히 보강합니다.
alter table public.idp_branch_profiles enable row level security;
alter table public.idp_branch_officers enable row level security;

grant select on public.idp_branch_profiles, public.idp_branch_officers to anon, authenticated;
grant insert, update, delete on public.idp_branch_profiles, public.idp_branch_officers to authenticated;

do $$
begin
  if to_regclass('public.idp_branch_officers_id_seq') is not null then
    execute 'grant usage, select on sequence public.idp_branch_officers_id_seq to authenticated';
  end if;
end $$;

-- 관리자 이메일이 맞는지 확인용(결과는 SQL Editor에 표시됩니다.)
select 'IDP v3.2.1 HOTFIX READY' as result;
